name: Build and deploy .NET application to container app aicatchgameweb-app-2025012210482
on:
  push:
    branches:
    - main


env:
  CONTAINER_APP_CONTAINER_NAME: aicatchgameweb
  CONTAINER_APP_NAME: aicatchgameweb-app-2025012210482
  CONTAINER_APP_RESOURCE_GROUP_NAME: AiCatchGame
  CONTAINER_REGISTRY_LOGIN_SERVER: aicatchgamereg.azurecr.io
  DOCKER_FILE_PATH: AiCatchGame.Web/Dockerfile
  PROJECT_NAME_FOR_DOCKER: aicatchgameweb
permissions:
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.aicatchgamereg_USERNAME_327B }}
        password: ${{ secrets.aicatchgamereg_PASSWORD_327B }}
    - name: Build and push container image to registry
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
        file: ${{ env.DOCKER_FILE_PATH }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.aicatchgameweb_app_2025012210482_SPN }}
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7A89D9E4044042DAAAEC0C34E8E65A14 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1D8FA58F6C0A46528D0A6D91878B5FFB }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8A401AC39DF34E90BD58B28BDA9A78DC }}
    - name: Deploy to containerapp
      uses: azure/CLI@v2
      with:
        inlineScript: >
          az config set extension.use_dynamic_install=yes_without_prompt

          az containerapp registry set --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --server ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} --username ${{ secrets.aicatchgamereg_USERNAME_327B }} --password ${{ secrets.aicatchgamereg_PASSWORD_327B }}

          az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --container-name ${{ env.CONTAINER_APP_CONTAINER_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --image ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
    - name: logout
      run: >
        az logout
